export const MTGO_COMMANDER_WORKSHOP_NAMES = [
  "Abhorrent Overlord",
  "Abrupt Decay",
  "Absorb",
  "Abundance",
  "Academy Manufactor",
  "Academy Rector",
  "Academy Ruins",
  "Accomplished Alchemist",
  "Ad Nauseam",
  "Adaptive Automaton",
  "Adarkar Valkyrie",
  "Adarkar Wastes",
  "Admiral Beckett Brass",
  "Aegis Angel",
  "Aether Channeler",
  "Aetherflux Reservoir",
  "Aetherspouts",
  "Aggravated Assault",
  "Aggressive Mining",
  "Ajani's Chosen",
  "Akiri, Fearless Voyager",
  "Akroan Horse",
  "Akroma, Angel of Fury",
  "Akroma, Angel of Wrath",
  "Akroma's Vengeance",
  "Akuta, Born of Ash",
  "Alchemist's Refuge",
  "Alela, Artful Provocateur",
  "All That Glitters",
  "All-Seeing Arbiter",
  "Altar of Dementia",
  "Altar of the Brood",
  "Altered Ego",
  "Ambition's Cost",
  "Ancient Amphitheater",
  "Ancient Den",
  "Ancient Greenwarden",
  "Angel of Destiny",
  "Angel of Glory's Rise",
  "Angel of Invention",
  "Angel of Jubilation",
  "Angel of Serenity",
  "Angel of the Ruins",
  "Angelfire Ignition",
  "Angelic Arbiter",
  "Angelic Chorus",
  "Angelic Destiny",
  "Angelic Skirmisher",
  "Angel's Grace",
  "Anger",
  "Angrath's Marauders",
  "Anim Pakal, Thousandth Moon",
  "Animal Sanctuary",
  "Animar, Soul of Elements",
  "Animist's Awakening",
  "Anointed Procession",
  "Apex of Power",
  "Approach of the Second Sun",
  "Arachnogenesis",
  "Arasta of the Endless Web",
  "Arcades, the Strategist",
  "Arcane Adaptation",
  "Arcane Denial",
  "Arcane Melee",
  "Arcane Signet",
  "Arcanis the Omnipotent",
  "Arcbond",
  "Arch of Orazca",
  "Archangel Avacyn",
  "Archangel of Strife",
  "Archangel of Thune",
  "Archangel of Tithes",
  "Archfiend of Depravity",
  "Archfiend of Ifnir",
  "Archmage Emeritus",
  "Archon of Justice",
  "Archon of Sun's Grace",
  "Archpriest of Shadows",
  "Arcum Dagsson",
  "Argentum Armor",
  "Arixmethes, Slumbering Isle",
  "Army of the Damned",
  "Artificer's Intuition",
  "Aryel, Knight of Windgrace",
  "As Foretold",
  "Ascendant Packleader",
  "Asceticism",
  "Ash Barrens",
  "Ashaya, Soul of the Wild",
  "Ashen Rider",
  "Assault Formation",
  "Assemble the Legion",
  "Astor, Bearer of Blades",
  "Astral Cornucopia",
  "Atarka, World Render",
  "Atemsis, All-Seeing",
  "Athreos, Shroud-Veiled",
  "Atraxa, Praetors' Voice",
  "Atsushi, the Blazing Sky",
  "Attrition",
  "Aura Shards",
  "Aurelia, the Warleader",
  "Aurelia's Fury",
  "Auriok Windwalker",
  "Austere Command",
  "Authority of the Consuls",
  "Avacyn, Guardian Angel",
  "Avatar of Woe",
  "Avenger of Zendikar",
  "Awakening of Vitu-Ghazi",
  "Awakening Zone",
  "Ayula, Queen Among Bears",
  "Ayula's Influence",
  "Azami, Lady of Scrolls",
  "Azor, the Lawbringer",
  "Azor's Elocutors",
  "Backdraft Hellkite",
  "Balefire Dragon",
  "Balefire Liege",
  "Baleful Force",
  "Baleful Mastery",
  "Baleful Strix",
  "Baneslayer Angel",
  "Baral, Chief of Compliance",
  "Baral's Expertise",
  "Bard Class",
  "Barkchannel Pathway",
  "Barrin, Tolarian Archmage",
  "Basilisk Collar",
  "Basri's Lieutenant",
  "Bastion Protector",
  "Batterskull",
  "Battlefield Forge",
  "Bazaar Trader",
  "Beacon of Tomorrows",
  "Beacon of Unrest",
  "Bear Umbra",
  "Bearscape",
  "Beast Whisperer",
  "Beast Within",
  "Beastmaster Ascension",
  "Bedrock Tortoise",
  "Bident of Thassa",
  "Biomancer's Familiar",
  "Biomass Mutation",
  "Biovisionary",
  "Birds of Paradise",
  "Bishop of Wings",
  "Bitterblossom",
  "Black Sun's Twilight",
  "Blackblade Reforged",
  "Blackcleave Cliffs",
  "Blacklance Paragon",
  "Blade Historian",
  "Blade of Selves",
  "Blade of the Oni",
  "Blade Splicer",
  "Bladewing the Risen",
  "Blasphemous Act",
  "Blast Zone",
  "Blasting Station",
  "Blatant Thievery",
  "Blazing Archon",
  "Blazing Shoal",
  "Blight Herder",
  "Blightsteel Colossus",
  "Blind Obedience",
  "Blinkmoth Urn",
  "Bloated Contaminator",
  "Bloated Processor",
  "Blood Crypt",
  "Blood on the Snow",
  "Bloodchief Ascension",
  "Bloodgift Demon",
  "Bloodline Keeper",
  "Bloodspore Thrinax",
  "Bloom Tender",
  "Blue Sun's Twilight",
  "Blue Sun's Zenith",
  "Body Snatcher",
  "Bogardan Hellkite",
  "Bojuka Bog",
  "Bolas's Citadel",
  "Boldwyr Heavyweights",
  "Bonehoard",
  "Bonescythe Sliver",
  "Boon Reflection",
  "Bootleggers' Stash",
  "Borborygmos Enraged",
  "Borderland Behemoth",
  "Boros Charm",
  "Boundless Realms",
  "Bow of Nylea",
  "Brago, King Eternal",
  "Braids, Conjurer Adept",
  "Brainstorm",
  "Branchloft Pathway",
  "Brash Taunter",
  "Brass's Bounty",
  "Brass's Tunnel-Grinder",
  "Breach the Multiverse",
  "Breath of Fury",
  "Breeches, Eager Pillager",
  "Breeding Pool",
  "Breya, Etherium Shaper",
  "Briar Hydra",
  "Brightclimb Pathway",
  "Brilliant Restoration",
  "Bring to Light",
  "Bringer of the Black Dawn",
  "Bringer of the Blue Dawn",
  "Bringer of the Green Dawn",
  "Bringer of the Last Gift",
  "Bringer of the Red Dawn",
  "Bringer of the White Dawn",
  "Brion Stoutarm",
  "Bristling Hydra",
  "Brokers Ascendancy",
  "Broodmate Dragon",
  "Brudiclad, Telchor Engineer",
  "Bruna, Light of Alabaster",
  "Bruna, the Fading Light",
  "Brushland",
  "Brutal Hordechief",
  "Bruvac the Grandiloquent",
  "Burning Earth",
  "Burning of Xinye",
  "Burning-Rune Demon",
  "By Invitation Only",
  "Cabal Coffers",
  "Cabal Stronghold",
  "Cackling Counterpart",
  "Caged Sun",
  "Cairn Wanderer",
  "Caldera Hellion",
  "Calix, Destiny's Hand",
  "Camaraderie",
  "Canopy Tactician",
  "Canopy Vista",
  "Canyon Slough",
  "Captain of the Watch",
  "Captivating Vampire",
  "Cascade Bluffs",
  "Cascading Cataracts",
  "Castle Embereth",
  "Castle Garenbrig",
  "Castle Vantress",
  "Cataclysmic Gearhulk",
  "Cathars' Crusade",
  "Cavalier of Dawn",
  "Cavalier of Flame",
  "Cavalier of Gales",
  "Cavalier of Night",
  "Caves of Koilos",
  "Celestial Ancient",
  "Celestial Colonnade",
  "Celestial Dawn",
  "Cemetery Illuminator",
  "Cemetery Reaper",
  "Cemetery Tampering",
  "Chain of Vapor",
  "Chain Reaction",
  "Chainer, Dementia Master",
  "Chainer, Nightmare Adept",
  "Chameleon Colossus",
  "Champion of Dusk",
  "Champion of Lambholt",
  "Champion of Rhonas",
  "Champion of Stray Souls",
  "Champion's Helm",
  "Chancellor of the Annex",
  "Chancellor of the Forge",
  "Chandra, Pyromaster",
  "Chandra's Ignition",
  "Chandra's Incinerator",
  "Chaos Warp",
  "Charmbreaker Devils",
  "Chasm Skulker",
  "Chatterfang, Squirrel General",
  "Child of Alara",
  "Chittering Witch",
  "Chitterspitter",
  "Choked Estuary",
  "Chromanticore",
  "Chromatic Lantern",
  "Chrome Host Seedshark",
  "Cinder Glade",
  "Cindervines",
  "Circle of Dreams Druid",
  "City on Fire",
  "Citywide Bust",
  "Claws of Gix",
  "Cleansing Nova",
  "Clickslither",
  "Cliffside Rescuer",
  "Clone",
  "Cloud Key",
  "Cloudshredder Sliver",
  "Cloudsteel Kirin",
  "Cloudstone Curio",
  "Cloudthresher",
  "Coalition Relic",
  "Coat of Arms",
  "Cold-Eyed Selkie",
  "Collective Effort",
  "Combat Celebrant",
  "Combustible Gearhulk",
  "Comet Storm",
  "Command Tower",
  "Commandeer",
  "Commit/Memory",
  "Commune with Lava",
  "Conduit of Ruin",
  "Conflux",
  "Confounding Conundrum",
  "Conjurer's Closet",
  "Connive/Concoct",
  "Conqueror's Flail",
  "Conqueror's Galleon",
  "Conspiracy",
  "Consume the Meek",
  "Consuming Aberration",
  "Consuming Tide",
  "Consuming Vapors",
  "Contagion Engine",
  "Contested Cliffs",
  "Control Magic",
  "Copperline Gorge",
  "Copy Enchantment",
  "Coralhelm Chronicler",
  "Cordial Vampire",
  "Corrupted Grafstone",
  "Cosima, God of the Voyage",
  "Cosmos Elixir",
  "Counterflux",
  "Courser of Kruphix",
  "Court of Locthwain",
  "Court of Vantress",
  "Crackle with Power",
  "Crater Hellion",
  "Creeping Renaissance",
  "Creeping Tar Pit",
  "Crested Sunmare",
  "Crippling Fear",
  "Cromat",
  "Crosis's Charm",
  "Crucible of Fire",
  "Crucible of the Spirit Dragon",
  "Crucible of Worlds",
  "Cruel Ultimatum",
  "Crush of Tentacles",
  "Crux of Fate",
  "Crypt Ghast",
  "Cryptolith Rite",
  "Crystalline Sliver",
  "Culling Ritual",
  "Cultivator's Caravan",
  "Cultural Exchange",
  "Curse of Leeches",
  "Curse of the Swine",
  "Cut Your Losses",
  "Cyclonic Rift",
  "Dack's Duplicate",
  "Damn",
  "Damnable Pact",
  "Damnation",
  "Dance of the Manse",
  "Danitha, Benalia's Hope",
  "Darigaaz's Charm",
  "Daring Thief",
  "Dark Confidant",
  "Dark Prophecy",
  "Darkslick Shores",
  "Darksteel Forge",
  "Darksteel Juggernaut",
  "Darksteel Plate",
  "Dauntless Escort",
  "Day of Judgment",
  "Daybreak Coronet",
  "Deadbridge Chant",
  "Deadeye Navigator",
  "Deafening Clarion",
  "Death Baron",
  "Deathbringer Thoctar",
  "Deathrender",
  "Deathrite Shaman",
  "Death's Presence",
  "Decadent Dragon",
  "Deceiver of Form",
  "Decree of Justice",
  "Decree of Pain",
  "Decree of Silence",
  "Deep Forest Hermit",
  "Defile",
  "Defiler of Dreams",
  "Defiler of Vigor",
  "Deflecting Palm",
  "Delina, Wild Mage",
  "Delusions of Mediocrity",
  "Demon of Dark Schemes",
  "Demonic Embrace",
  "Demonlord Belzenlok",
  "Dennick, Pious Apprentice",
  "Depala, Pilot Exemplar",
  "Dermotaxi",
  "Descendants' Path",
  "Desolate Lighthouse",
  "Desolation Angel",
  "Desolation Giant",
  "Desolation Twin",
  "Destructive Force",
  "Detention Sphere",
  "Devastating Summons",
  "Devastation Tide",
  "Diabolic Revelation",
  "Dictate of Erebos",
  "Dictate of Karametra",
  "Dictate of Kruphix",
  "Dictate of the Twin Gods",
  "Dig Through Time",
  "Diluvian Primordial",
  "Diminishing Returns",
  "Dimir Doppelganger",
  "Dire Fleet Daredevil",
  "Diregraf Colossus",
  "Disallow",
  "Disciple of Bolas",
  "Dismiss into Dream",
  "Displacement Wave",
  "Disrupting Shoal",
  "Divine Reckoning",
  "Divine Visitation",
  "Divinity of Pride",
  "Djeru and Hazoret",
  "Dolmen Gate",
  "Domri, Anarch of Bolas",
  "Doomed Necromancer",
  "Doomskar",
  "Doomwake Giant",
  "Door of Destinies",
  "Double Vision",
  "Doubling Season",
  "Dovin's Veto",
  "Dowsing Dagger",
  "Draconic Intervention",
  "Dragon Throne of Tarkir",
  "Dragonlord Atarka",
  "Dragonlord Ojutai",
  "Dragonlord's Prerogative",
  "Dragonmaster Outcast",
  "Dragon's Hoard",
  "Dragonspeaker Shaman",
  "Dragonwing Glider",
  "Drakuseth, Maw of Flames",
  "Dralnu, Lich Lord",
  "Drana and Linvala",
  "Drana, Liberator of Malakir",
  "Dread",
  "Dread Presence",
  "Dread Return",
  "Dream Devourer",
  "Dream Eater",
  "Dream Trawler",
  "Dreamborn Muse",
  "Dreamstealer",
  "Drizzt Do'Urden",
  "Drogskol Reaver",
  "Dromoka, the Eternal",
  "Dross Harvester",
  "Druids' Repository",
  "Dual Casting",
  "Dualcaster Mage",
  "Duneblast",
  "Dune-Brood Nephilim",
  "Dungeon Delver",
  "Duplicant",
  "Dusk/Dawn",
  "Dwarven Miner",
  "Dwarven Recruiter",
  "Dwynen, Gilt-Leaf Daen",
  "Earthquake",
  "Edgar, Charmed Groom",
  "Edric, Spymaster of Trest",
  "Eerie Ultimatum",
  "Eidolon of Blossoms",
  "Eidolon of Countless Battles",
  "Eladamri's Call",
  "Elbrus, the Binding Blade",
  "Eldrazi Displacer",
  "Eldrazi Mimic",
  "Eldrazi Monument",
  "Eldrazi Temple",
  "Electrodominance",
  "Elenda, the Dusk Rose",
  "Elesh Norn, Grand Cenobite",
  "Eligeth, Crossroads Augur",
  "Elspeth Resplendent",
  "Elspeth Tirel",
  "Elspeth, Sun's Champion",
  "Elvish Archdruid",
  "Elvish Champion",
  "Elvish Dreadlord",
  "Elvish Piper",
  "Embereth Skyblazer",
  "Embermaw Hellion",
  "Emergency Powers",
  "Emeria Shepherd",
  "Emeria, the Sky Ruin",
  "Empyrial Plate",
  "Empyrial Storm",
  "Emrakul's Evangel",
  "Enchantress's Presence",
  "Endbringer",
  "Endless Detour",
  "Endless One",
  "Endless Ranks of the Dead",
  "End-Raze Forerunners",
  "Enduring Ideal",
  "Engulf the Shore",
  "Enigma Thief",
  "Ephara, God of the Polis",
  "Epic Experiment",
  "Epiphany at the Drownyard",
  "Erebos, God of the Dead",
  "Erebos's Intervention",
  "Errant and Giada",
  "Errant, Street Artist",
  "Erratic Portal",
  "Escape to the Wilds",
  "Esika, God of the Tree",
  "Essence of Orthodoxy",
  "Etali, Primal Storm",
  "Etched Champion",
  "Ethereal Absolution",
  "Ethersworn Adjudicator",
  "Ethersworn Canonist",
  "Evacuation",
  "Evil Twin",
  "Evolutionary Leap",
  "Evra, Halcyon Witness",
  "Exotic Orchard",
  "Expel the Interlopers",
  "Experimental Confectioner",
  "Expressive Iteration",
  "Exquisite Blood",
  "Extraplanar Lens",
  "Eye of Ugin",
  "Eye of Vecna",
  "Ezuri, Claw of Progress",
  "Ezuri, Renegade Leader",
  "Ezuri, Stalker of Spheres",
  "Fabled Passage",
  "Faceless Haven",
  "Fade from History",
  "Faeburrow Elder",
  "Faerie Formation",
  "Faerie Seer",
  "Faith's Reward",
  "Fate Unraveler",
  "Fated Return",
  "Fateful Showdown",
  "Fatespinner",
  "Fathom Mage",
  "Fblthp, the Lost",
  "Feather, the Redeemed",
  "Feed the Pack",
  "Felidar Retreat",
  "Felidar Sovereign",
  "Feline Sovereign",
  "Feral Encounter",
  "Feral Hydra",
  "Feroz's Ban",
  "Fervent Champion",
  "Fervent Charge",
  "Fervent Mastery",
  "Fervor",
  "Fetid Heath",
  "Fetid Pools",
  "Field of the Dead",
  "Fiery Emancipation",
  "Fighter Class",
  "Finale of Glory",
  "Find/Finality",
  "Fire-Lit Thicket",
  "Firemane Avenger",
  "Firemind's Foresight",
  "Fist of Suns",
  "Flamerush Rider",
  "Flamescroll Celebrant",
  "Flameshadow Conjuring",
  "Flicker",
  "Flickerform",
  "Flood of Tears",
  "Flooded Grove",
  "Florian, Voldaren Scion",
  "Flumph",
  "Flying Crane Technique",
  "Folio of Fancies",
  "Font of Agonies",
  "Font of Mythos",
  "Forbidden Orchard",
  "Foreboding Ruins",
  "Forgestoker Dragon",
  "Forgotten Creation",
  "Forsworn Paladin",
  "Fortified Village",
  "Fractured Sanity",
  "Fraying Omnipotence",
  "Fresh Meat",
  "From Beyond",
  "Frontier Siege",
  "Frontline Medic",
  "Frost Titan",
  "Frostboil Snarl",
  "Fumiko the Lowblood",
  "Furnace of Rath",
  "Fury of the Horde",
  "Furycalm Snarl",
  "Future Sight",
  "Gaddock Teeg",
  "Gadrak, the Crown-Scourge",
  "Gadwick, the Wizened",
  "Gala Greeters",
  "Galazeth Prismari",
  "Galerider Sliver",
  "Gamble",
  "Game Trail",
  "Gargos, Vicious Watcher",
  "Garruk, Primal Hunter",
  "Garth One-Eye",
  "Gate to the Aether",
  "Gather Specimens",
  "Gavony Township",
  "Gaze of Granite",
  "Geier Reach Sanitarium",
  "Geist-Honored Monk",
  "General Ferrous Rokiric",
  "General Marhault Elsdragon",
  "General Tazri",
  "General's Kabuto",
  "Genesis Chamber",
  "Genesis Hydra",
  "Genesis Ultimatum",
  "Genesis Wave",
  "Genju of the Realm",
  "Geralf, Visionary Stitcher",
  "Ghalta and Mavren",
  "Ghalta, Primal Hunger",
  "Ghirapur Orrery",
  "Ghostly Pilferer",
  "Ghostly Prison",
  "Giada, Font of Hope",
  "Giant Adephage",
  "Gift of Immortality",
  "Gild",
  "Gilded Lotus",
  "Gilt-Leaf Palace",
  "Gisa and Geralf",
  "Gisa, Glorious Resurrector",
  "Gisela, Blade of Goldnight",
  "Gisela, the Broken Blade",
  "Gishath, Sun's Avatar",
  "Glen Elendra Archmage",
  "Glen Elendra Liege",
  "Glimpse of Nature",
  "Glimpse the Unthinkable",
  "Glint Raker",
  "Glint-Eye Nephilim",
  "Glissa, Herald of Predation",
  "Glissa, the Traitor",
  "Glistening Dawn",
  "Goblin Bombardment",
  "Goblin Chainwhirler",
  "Goblin Diplomats",
  "Goblin Engineer",
  "Goblin Marshal",
  "Goblin Razerunners",
  "God-Eternal Rhonas",
  "Godless Shrine",
  "Godo, Bandit Warlord",
  "Golden Argosy",
  "Gonti, Lord of Luxury",
  "Goreclaw, Terror of Qal Sisma",
  "Goring Ceratops",
  "Goro-Goro, Disciple of Ryusei",
  "Grafdigger's Cage",
  "Grafted Butcher",
  "Grakmaw, Skyclave Ravager",
  "Grand Abolisher",
  "Grand Arbiter Augustin IV",
  "Grand Architect",
  "Grand Coliseum",
  "Grasp of Fate",
  "Gratuitous Violence",
  "Grave Pact",
  "Grave Titan",
  "Graveborn Muse",
  "Gravebreaker Lamia",
  "Gravecrawler",
  "Graven Cairns",
  "Gravespawn Sovereign",
  "Gravewaker",
  "Grazilaxx, Illithid Scholar",
  "Great Furnace",
  "Greater Auramancy",
  "Greater Gargadon",
  "Greater Good",
  "Greenwarden of Murasa",
  "Grid Monitor",
  "Grim Backwoods",
  "Grim Poppet",
  "Grimgrin, Corpse-Born",
  "Grove of the Burnwillows",
  "Growing Rites of Itlimoc",
  "Gruesome Menagerie",
  "Gruesome Slaughter",
  "Gruff Triplets",
  "Guardian of Faith",
  "Guardian Project",
  "Guided Passage",
  "Guile",
  "Gwenna, Eyes of Gaea",
  "Gyre Sage",
  "Gyruda, Doom of Depths",
  "Haakon, Stromgald Scourge",
  "Hadana's Climb",
  "Hagra Mauling",
  "Hajar, Loyal Bodyguard",
  "Halana and Alena, Partners",
  "Hall of Heliod's Generosity",
  "Hall of Oracles",
  "Hallowed Fountain",
  "Halvar, God of Battle",
  "Hamletback Goliath",
  "Hammer of Nazahn",
  "Hammer of Purphoros",
  "Hammerfist Giant",
  "Hand of the Praetors",
  "Hand of Vecna",
  "Hanna, Ship's Navigator",
  "Hanna's Custody",
  "Harbin, Vanguard Aviator",
  "Hardened Scales",
  "Harmless Offering",
  "Harmonic Prodigy",
  "Harsh Mentor",
  "Harvester of Souls",
  "Haunting Voyage",
  "Haven of the Spirit Dragon",
  "Haywire Mite",
  "He Who Hungers",
  "Headless Rider",
  "Heartbeat of Spring",
  "Heartless Hidetsugu",
  "Heartless Summoning",
  "Heartwood Storyteller",
  "Heat Shimmer",
  "Hedron Matrix",
  "Heliod's Intervention",
  "Hellkite Charger",
  "Hellkite Tyrant",
  "Hellrider",
  "Helm of Kaldra",
  "Helm of the Gods",
  "Helm of the Host",
  "Herald of Anguish",
  "Herald of Secret Streams",
  "Herald of the Pantheon",
  "Herald of War",
  "Hero of Bladehold",
  "Heroic Intervention",
  "Hidetsugu and Kairi",
  "Hidetsugu, Devouring Chaos",
  "Hinata, Dawn-Crowned",
  "Hissing Quagmire",
  "Hit the Mother Lode",
  "Hoard Hauler",
  "Hoarding Broodlord",
  "Hofri Ghostforge",
  "Hollow One",
  "Hooded Hydra",
  "Hope of Ghirapur",
  "Hopeful Initiate",
  "Horde of Notions",
  "Hornet Nest",
  "Hornet Queen",
  "Horobi, Death's Wail",
  "Hostage Taker",
  "Hostile Takeover",
  "Hostility",
  "Hour of Promise",
  "Hour of Reckoning",
  "Hour of Revelation",
  "Howl of the Horde",
  "Howling Mine",
  "Howling Moon",
  "Howlpack Piper",
  "Hungering Hydra",
  "Hunted Dragon",
  "Hunted Horror",
  "Hunted Troll",
  "Hunter's Prowess",
  "Huntmaster of the Fells",
  "Hurricane",
  "Hushwing Gryff",
  "Hydra Broodmaster",
  "Hydroid Krasis",
  "Hypnotic Siren",
  "Hypnox",
  "Icon of Ancestry",
  "Identity Crisis",
  "Idyllic Tutor",
  "Illusionist's Bracers",
  "Illusionist's Gambit",
  "Imp's Mischief",
  "In Garruk's Wake",
  "In the Web of War",
  "Iname, Death Aspect",
  "Incandescent Aria",
  "Incendiary Command",
  "Increasing Ambition",
  "Increasing Devotion",
  "Increasing Savagery",
  "Increasing Vengeance",
  "Incubation Druid",
  "Indestructibility",
  "Indomitable Archangel",
  "Inevitable Betrayal",
  "Inexorable Tide",
  "Inferno Titan",
  "Inga and Esika",
  "Ingenious Mastery",
  "Ingenious Prodigy",
  "Ink-Eyes, Servant of Oni",
  "Ink-Treader Nephilim",
  "Inscription of Abundance",
  "Inscription of Insight",
  "Inspired Ultimatum",
  "Inspiring Statuary",
  "Instigator Gang",
  "Insurrection",
  "Intet, the Dreamer",
  "Intrepid Paleontologist",
  "Invasion of Alara",
  "Invasion of Innistrad",
  "Invasion of Segovia",
  "Invasion of Theros",
  "Inventors' Fair",
  "Investigator's Journal",
  "Invoke Calamity",
  "Iridian Maelstrom",
  "Iroas, God of Victory",
  "Iron Maiden",
  "Irrigated Farmland",
  "Isamaru, Hound of Konda",
  "Ishkanah, Grafwidow",
  "Isperia the Inscrutable",
  "Isperia, Supreme Judge",
  "Isshin, Two Heavens as One",
  "It That Betrays",
  "Ixidron",
  "Izoni, Thousand-Eyed",
  "Jace Beleren",
  "Jace, Mirror Mage",
  "Jace's Sanctum",
  "Jacob Hauken, Inspector",
  "Jadelight Spelunker",
  "Jarad, Golgari Lich Lord",
  "Jarad's Orders",
  "Jareth, Leonine Titan",
  "Jaxis, the Troublemaker",
  "Jaya's Immolating Inferno",
  "Jegantha, the Wellspring",
  "Jeleva, Nephalia's Scourge",
  "Jeskai Ascendancy",
  "Jetmir, Nexus of Revels",
  "Jhoira, Weatherlight Captain",
  "Jin-Gitaxias, Core Augur",
  "Jinnie Fay, Jetmir's Second",
  "Jirina, Dauntless General",
  "Jodah, Archmage Eternal",
  "Jodah, the Unifier",
  "Jolrael, Empress of Beasts",
  "Jolrael, Voice of Zhalfir",
  "Jor Kadeen, First Goldwarden",
  "Jor Kadeen, the Prevailer",
  "Josu Vess, Lich Knight",
  "Jugan, the Rising Star",
  "Junji, the Midnight Sky",
  "Kaalia of the Vast",
  "Kaalia, Zenith Seeker",
  "Kaervek the Merciless",
  "Kagemaro, First to Suffer",
  "Kairi, the Swirling Sky",
  "Kaito, Dancing Shadow",
  "Kalitas, Traitor of Ghet",
  "Kalonian Hydra",
  "Kamahl's Druidic Vow",
  "Kambal, Consul of Allocation",
  "Kami of the Crescent Moon",
  "Karametra, God of Harvests",
  "Kari Zev's Expertise",
  "Karmic Guide",
  "Karmic Justice",
  "Karn, Legacy Reforged",
  "Karn's Bastion",
  "Karn's Temporal Sundering",
  "Karona, False God",
  "Karplusan Forest",
  "Karrthus, Tyrant of Jund",
  "Karumonix, the Rat King",
  "Kataki, War's Wage",
  "Katilda, Dawnhart Martyr",
  "Katilda, Dawnhart Prime",
  "Keiga, the Tide Star",
  "Kenrith, the Returned King",
  "Kess, Dissident Mage",
  "Kessig Cagebreakers",
  "Kessig Wolf Run",
  "Kethis, the Hidden Hand",
  "Key to the City",
  "Kher Keep",
  "Killing Wave",
  "Kindred Dominance",
  "King Darien XLVIII",
  "King Macar, the Gold-Cursed",
  "King Narfi's Betrayal",
  "Kinjalli's Sunwing",
  "Kinnan, Bonder Prodigy",
  "Kinsbaile Cavalier",
  "Knacksaw Clique",
  "Knight Exemplar",
  "Knight of the White Orchid",
  "Knights' Charge",
  "Knowledge Exploitation",
  "Kodama of the West Tree",
  "Kogla and Yidaro",
  "Kogla, the Titan Ape",
  "Kokusho, the Evening Star",
  "Kolaghan's Command",
  "Kolvori, God of Kinship",
  "Konda, Lord of Eiganjo",
  "Konda's Banner",
  "Kor Spiritdancer",
  "Korvold, Fae-Cursed King",
  "Kothophed, Soul Hoarder",
  "Kozilek, Butcher of Truth",
  "Kozilek, the Great Distortion",
  "Krark-Clan Ironworks",
  "Krenko, Mob Boss",
  "Krenko, Tin Street Kingpin",
  "Kruphix, God of Horizons",
  "Kuldotha Forgemaster",
  "Kumena's Awakening",
  "Kuro, Pitlord",
  "Kykar, Wind's Fury",
  "Kyodai, Soul of Kamigawa",
  "Kyoki, Sanity's Eclipse",
  "Laboratory Maniac",
  "Languish",
  "Last Stand",
  "Lathliss, Dragon Queen",
  "Lavaclaw Reaches",
  "Lavinia of the Tenth",
  "Lazav, Dimir Mastermind",
  "Leadership Vacuum",
  "Legion Warboss",
  "Legion's Initiative",
  "Legion's Landing",
  "Lena, Selfless Champion",
  "Leonin Abunas",
  "Leonin Arbiter",
  "Leonin Lightscribe",
  "Leonin Warleader",
  "Leyline Immersion",
  "Leyline of Anticipation",
  "Leyline Tyrant",
  "Lich-Knights' Conquest",
  "Lich's Mastery",
  "Lier, Disciple of the Drowned",
  "Liesa, Forgotten Archangel",
  "Lifecrafter's Bestiary",
  "Life's Legacy",
  "Light of Sanction",
  "Lightmine Field",
  "Lightning Coils",
  "Liliana, Death's Majesty",
  "Liliana, Dreadhorde General",
  "Liliana, Heretical Healer",
  "Liliana's Contract",
  "Liliana's Mastery",
  "Liliana's Standard Bearer",
  "Lim-Dul's Vault",
  "Linvala, Keeper of Silence",
  "Linvala, Shield of Sea Gate",
  "Linvala, the Preserver",
  "Lion Sash",
  "Lithoform Engine",
  "Living Death",
  "Lizard Blades",
  "Llanowar Loamspeaker",
  "Llanowar Wastes",
  "Lodestone Myr",
  "Lolth, Spider Queen",
  "Lonis, Cryptozoologist",
  "Lord of the Forsaken",
  "Lord of the Void",
  "Lord Xander, the Collector",
  "Lorehold Command",
  "Lotus Cobra",
  "Loxodon Gatekeeper",
  "Loyal Guardian",
  "Loyal Warhound",
  "Lumbering Falls",
  "Luminarch Ascension",
  "Luminate Primordial",
  "Lurking Predators",
  "Lurrus of the Dream-Den",
  "Lyra Dawnbringer",
  "Maelstrom Archangel",
  "Maelstrom Nexus",
  "Maga, Traitor to Mortals",
  "Magda, Brazen Outlaw",
  "Magma Giant",
  "Magmaquake",
  "Magus of the Candelabra",
  "Magus of the Tabernacle",
  "Malcolm, Alluring Scoundrel",
  "Mana Flare",
  "Manabarbs",
  "Managorger Hydra",
  "Mangara, the Diplomat",
  "Marauding Raptor",
  "March of the Multitudes",
  "Marchesa, the Black Rose",
  "Marionette Master",
  "Mark of Asylum",
  "Marrow-Gnawer",
  "Marsh Flats",
  "Marshal's Anthem",
  "Martial Coup",
  "Marwyn, the Nurturer",
  "Mask of Griselbrand",
  "Maskwood Nexus",
  "Mass Manipulation",
  "Massacre",
  "Massacre Wurm",
  "Master Biomancer",
  "Master of Cruelties",
  "Master of Death",
  "Master of Etherium",
  "Master of the Feast",
  "Master Warcraft",
  "Mastermind's Acquisition",
  "Matter Reshaper",
  "Maul of the Skyclaves",
  "Mausoleum Secrets",
  "Mayael's Aria",
  "Mayor of Avabruck",
  "Mechanized Production",
  "Mechtitan Core",
  "Meeting of the Five",
  "Megantic Sliver",
  "Meloku the Clouded Mirror",
  "Memory Plunder",
  "Merciless Eviction",
  "Mercurial Spelldancer",
  "Mesmeric Orb",
  "Metallic Mimic",
  "Metallurgic Summonings",
  "Metalwork Colossus",
  "Michiko Konda, Truth Seeker",
  "Midnight Clock",
  "Mikaeus, the Lunarch",
  "Mikaeus, the Unhallowed",
  "Mikokoro, Center of the Sea",
  "Mimic Vat",
  "Mind Flayer",
  "Mind Grind",
  "Mind Shatter",
  "Mind Spring",
  "Mind Unbound",
  "Mindlink Mech",
  "Mindlock Orb",
  "Mind's Desire",
  "Mind's Dilation",
  "Mindslicer",
  "Mindsplice Apparatus",
  "Minion of the Mighty",
  "Mirage Mirror",
  "Mirari's Wake",
  "Mirrodin Besieged",
  "Mirror Entity",
  "Mirror March",
  "Mirror-Mad Phantasm",
  "Mirrormade",
  "Mirrorpool",
  "Mirrorweave",
  "Mirrorworks",
  "Mishra, Claimed by Gix",
  "Mistcutter Hydra",
  "Misthollow Griffin",
  "Mist-Syndicate Naga",
  "Mite Overseer",
  "Mizzium Mortars",
  "Mizzium Tank",
  "Mizzix's Mastery",
  "Moderation",
  "Mogg Alarm",
  "Mogg Infestation",
  "Moira, Urborg Haunt",
  "Molten Disaster",
  "Molten Primordial",
  "Monastery Siege",
  "Mordant Dragon",
  "Mordenkainen",
  "Morophon, the Boundless",
  "Mortal Combat",
  "Mortivore",
  "Mosswort Bridge",
  "Mox Tantalite",
  "Muldrotha, the Gravetide",
  "Murderous Rider",
  "Murmuring Bosk",
  "Mutilate",
  "Mycoloth",
  "Mycosynth Golem",
  "Mycosynth Lattice",
  "Myojin of Cleansing Fire",
  "Myojin of Life's Web",
  "Myojin of Night's Reach",
  "Myojin of Seeing Winds",
  "Myr Battlesphere",
  "Myr Matrix",
  "Myr Propagator",
  "Myr Reservoir",
  "Myr Superion",
  "Myr Turbine",
  "Myr Welder",
  "Myriad Landscape",
  "Mysterious Limousine",
  "Mystic Confluence",
  "Mystic Forge",
  "Mystic Gate",
  "Mystic Snake",
  "Mystical Dispute",
  "Mystical Tutor",
  "Nadaar, Selfless Paladin",
  "Nahiri, Forged in Fury",
  "Nahiri, Heir of the Ancients",
  "Nahiri's Resolve",
  "Najeela, the Blade-Blossom",
  "Narset, Enlightened Exile",
  "Narset, Enlightened Master",
  "Narset's Reversal",
  "Naru Meha, Master Wizard",
  "Nashi, Moon Sage's Scion",
  "Nashi, Moon's Legacy",
  "Nature's Will",
  "Necroblossom Snarl",
  "Necroduality",
  "Necromancer's Covenant",
  "Necroskitter",
  "Necrotic Ooze",
  "Needle Spires",
  "Nefarox, Overlord of Grixis",
  "Nekusar, the Mindrazer",
  "Nemesis of Reason",
  "Nephalia Drownyard",
  "Nessian Boar",
  "Nessian Wilds Ravager",
  "Nether Traitor",
  "Nettlecyst",
  "Never/Return",
  "Nevermore",
  "Nevinyrral's Disk",
  "Nezahal, Primal Tide",
  "Niambi, Esteemed Speaker",
  "Nicol Bolas, Dragon-God",
  "Nicol Bolas, God-Pharaoh",
  "Nicol Bolas, Planeswalker",
  "Nicol Bolas, the Ravager",
  "Nighthawk Scavenger",
  "Nighthowler",
  "Night's Whisper",
  "Nightshade Harvester",
  "Nihilith",
  "Nim Deathmantle",
  "Nimble Obstructionist",
  "Nimbus Maze",
  "Nine Lives",
  "Nissa, Resurgent Animist",
  "Nissa, Steward of Elements",
  "Nissa, Who Shakes the World",
  "Nissa's Revelation",
  "Niv-Mizzet Reborn",
  "Niv-Mizzet, Parun",
  "Niv-Mizzet, Supreme",
  "Niv-Mizzet, the Firemind",
  "Noble Hierarch",
  "Noosegraf Mob",
  "Norin the Wary",
  "Norn's Annex",
  "Notion Thief",
  "Notorious Throng",
  "Noxious Gearhulk",
  "Noyan Dar, Roil Shaper",
  "Nykthos Paragon",
  "Nykthos, Shrine to Nyx",
  "Nylea, Keen-Eyed",
  "Nyxbloom Ancient",
  "Oath of Jace",
  "Oathkeeper, Takeno's Daisho",
  "Ob Nixilis Reignited",
  "Ob Nixilis, Captive Kingpin",
  "Ob Nixilis, the Fallen",
  "Ob Nixilis, Unshackled",
  "Obelisk of Urd",
  "Oblation",
  "Oblivion Sower",
  "Oblivion Stone",
  "Obsidian Charmaw",
  "Ochre Jelly",
  "Odric, Lunarch Marshal",
  "Ognis, the Dragon's Lash",
  "Ogre Battledriver",
  "Ogre Slumlord",
  "Ohran Viper",
  "Ojutai, Soul of Winter",
  "Ojutai's Command",
  "Okina, Temple to the Grandfathers",
  "Old Gnawbone",
  "Old Stickfingers",
  "Oloro, Ageless Ascetic",
  "Omnath, Locus of All",
  "Omnath, Locus of Mana",
  "Omnath, Locus of Rage",
  "Omniscience",
  "On Thin Ice",
  "Ondu Inversion",
  "Oona, Queen of the Fae",
  "Open the Graves",
  "Open the Vaults",
  "Oracle of Mul Daya",
  "Oran-Rief Hydra",
  "Oran-Rief, the Vastwood",
  "Orb of Dragonkind",
  "Orcus, Prince of Undeath",
  "Orim's Chant",
  "Oriq Loremage",
  "Ormos, Archive Keeper",
  "Orthion, Hero of Lavabrink",
  "Oswald Fiddlebender",
  "Otherworld Atlas",
  "Out of Time",
  "Outpost Siege",
  "Overcharged Amalgam",
  "Overgrown Tomb",
  "Overwhelming Stampede",
  "Pack Leader",
  "Pack Rat",
  "Pact of Negation",
  "Painful Quandary",
  "Painful Truths",
  "Palace Siege",
  "Paladin Class",
  "Pandemonium",
  "Panharmonicon",
  "Paradoxical Outcome",
  "Parallax Wave",
  "Parallel Lives",
  "Parhelion II",
  "Pariah",
  "Part the Waterveil",
  "Pashalik Mons",
  "Past in Flames",
  "Patriarch's Bidding",
  "Patron of the Nezumi",
  "Peacewalker Colossus",
  "Peer into the Abyss",
  "Pentavus",
  "Perennial Behemoth",
  "Perilous Vault",
  "Perplexing Chimera",
  "Persist",
  "Pest Infestation",
  "Pestilence Demon",
  "Phantasmal Image",
  "Pharika, God of Affliction",
  "Phenax, God of Deception",
  "Phyrexian Arena",
  "Phyrexian Crusader",
  "Phyrexian Dragon Engine",
  "Phyrexian Hydra",
  "Phyrexian Metamorph",
  "Phyrexian Obliterator",
  "Phyrexian Plaguelord",
  "Phyrexian Rebirth",
  "Phyrexian Revoker",
  "Phyrexian Scriptures",
  "Phyrexian Swarmlord",
  "Phyrexian Unlife",
  "Phyrexian Vatmother",
  "Pia and Kiran Nalaar",
  "Pia Nalaar",
  "Pile On",
  "Piper of the Swarm",
  "Piru, the Volatile",
  "Plague Belcher",
  "Planar Bridge",
  "Planar Cleansing",
  "Planar Outburst",
  "Planewide Celebration",
  "Plargg and Nassari",
  "Platinum Angel",
  "Platinum Emperion",
  "Platoon Dispenser",
  "Plaza of Heroes",
  "Plea for Power",
  "Polluted Bonds",
  "Polukranos, Unchained",
  "Polymorph",
  "Polymorphist's Jest",
  "Port Town",
  "Possibility Storm",
  "Praetor's Counsel",
  "Praetor's Grasp",
  "Prairie Stream",
  "Priest of Fell Rites",
  "Prime Speaker Zegana",
  "Primeval Spawn",
  "Primevals' Glorious Rebirth",
  "Primordial Sage",
  "Pristine Angel",
  "Profane Tutor",
  "Professional Face-Breaker",
  "Progenitor Exarch",
  "Progenitor Mimic",
  "Progenitus",
  "Promise of Power",
  "Propaganda",
  "Prophetic Flamespeaker",
  "Protean Hulk",
  "Protean Raider",
  "Proteus Staff",
  "Prowling Serpopard",
  "Psychosis Crawler",
  "Puca's Mischief",
  "Pull from Tomorrow",
  "Puppeteer Clique",
  "Purity",
  "Purphoros, God of the Forge",
  "Putrefax",
  "Pyramid of the Pantheon",
  "Pyromancer's Swath",
  "Qasali Slingers",
  "Quarantine Field",
  "Quartzwood Crasher",
  "Quicksilver Amulet",
  "Quietus Spike",
  "Rabble Rousing",
  "Radiant Destiny",
  "Radiant Scrollwielder",
  "Raging Ravine",
  "Rags/Riches",
  "Raiyuu, Storm's Edge",
  "Rakdos the Defiler",
  "Rakdos, Lord of Riots",
  "Rakdos, the Showstopper",
  "Ral Zarek",
  "Ral, Storm Conduit",
  "Rally the Ancestors",
  "Rampaging Baloths",
  "Rampaging Ferocidon",
  "Ramunap Excavator",
  "Rankle, Master of Pranks",
  "Rankle's Prank",
  "Ratadrabik of Urborg",
  "Ratcatcher",
  "Rattleclaw Mystic",
  "Ravenous Baboons",
  "Razaketh, the Foulblooded",
  "Razia's Purification",
  "Razorlash Transmogrant",
  "Razorverge Thicket",
  "Read the Runes",
  "Reality Smasher",
  "Realmwalker",
  "Reanimate",
  "Reap the Past",
  "Reaper from the Abyss",
  "Reaper King",
  "Reckless Crew",
  "Recurring Insight",
  "Redcap Gutter-Dweller",
  "Reflecting Pool",
  "Reflections of Littjara",
  "Reforge the Soul",
  "Regal Bunnicorn",
  "Regisaur Alpha",
  "Reign of the Pit",
  "Reins of Power",
  "Reiterate",
  "Reiver Demon",
  "Relentless Assault",
  "Relic Seeker",
  "Rem Karolus, Stalwart Slayer",
  "Remorseful Cleric",
  "Render Silent",
  "Renegade Krasis",
  "Repercussion",
  "Requiem Angel",
  "Reshape",
  "Resplendent Angel",
  "Response/Resurgence",
  "Restless Reef",
  "Resurgent Belief",
  "Retether",
  "Retract",
  "Retribution of the Meek",
  "Return of the Wildspeaker",
  "Reveillark",
  "Revel in Riches",
  "Reverberate",
  "Reverence",
  "Reweave",
  "Reya Dawnbringer",
  "Rhox Faithmender",
  "Rhys the Exiled",
  "Rhys the Redeemed",
  "Riders of Gavony",
  "Rienne, Angel of Rebirth",
  "Righteous Authority",
  "Righteous Valkyrie",
  "Rin and Seri, Inseparable",
  "Ring of Three Wishes",
  "Ripjaw Raptor",
  "Riptide Laboratory",
  "Rise and Shine",
  "Rishkar, Peema Renegade",
  "Rishkar's Expertise",
  "Risona, Asari Commander",
  "Rite of Harmony",
  "Rite of Replication",
  "Rites of Flourishing",
  "Rith, Liberated Primeval",
  "Rivaz of the Claw",
  "River Kelpie",
  "River of Tears",
  "Riveteers Ascendancy",
  "Roaming Throne",
  "Rocco, Street Chef",
  "Rockfall Vale",
  "Role Reversal",
  "Rooftop Storm",
  "Rubblehulk",
  "Rude Awakening",
  "Rugged Prairie",
  "Ruinous Ultimatum",
  "Runaway Steam-Kin",
  "Rune-Scarred Demon",
  "Rune-Tail, Kitsune Ascendant",
  "Runic Armasaur",
  "Ruric Thar, the Unbowed",
  "Ryusei, the Falling Star",
  "Sacred Foundry",
  "Sacred Ground",
  "Sadistic Sacrament",
  "Saffi Eriksdotter",
  "Sage of Ancient Lore",
  "Sage of Hours",
  "Saheeli Rai",
  "Saheeli's Artistry",
  "Sai, Master Thopterist",
  "Sakashima the Impostor",
  "Salvaging Station",
  "Sanctum of All",
  "Sanctum of Ugin",
  "Sanctum Weaver",
  "Sangromancer",
  "Saproling Burst",
  "Saproling Symbiosis",
  "Sarkhan the Masterless",
  "Sarkhan Unbroken",
  "Sarkhan, Dragonsoul",
  "Sarkhan, Fireblood",
  "Sarkhan's Unsealing",
  "Saryth, the Viper's Fang",
  "Satoru Umezawa",
  "Satsuki, the Living Lore",
  "Savageborn Hydra",
  "Savior of Ollenbock",
  "Saw in Half",
  "Scalding Viper",
  "Scapeshift",
  "Scarecrone",
  "Scatter to the Winds",
  "Scattered Groves",
  "Scavenger Grounds",
  "Scavenging Ooze",
  "Scion of Oona",
  "Scion of the Ur-Dragon",
  "Scourge of Fleets",
  "Scourge of Skola Vale",
  "Scourge of Valkas",
  "Scrap Trawler",
  "Scrapyard Recombiner",
  "Sculpting Steel",
  "Scute Swarm",
  "Scythe of the Wretched",
  "Sea Gate Stormcaller",
  "Sea Gate Wreckage",
  "Seachrome Coast",
  "Search for Azcanta",
  "Seat of the Synod",
  "Secluded Glen",
  "Second Harvest",
  "Secure the Wastes",
  "Sedgemoor Witch",
  "See the Truth",
  "Seer's Sundial",
  "Seizan, Perverter of Truth",
  "Sekki, Seasons' Guide",
  "Selfless Glyphweaver",
  "Selfless Spirit",
  "Semblance Anvil",
  "Sephara, Sky's Blade",
  "Sepulchral Primordial",
  "Serra's Emissary",
  "Serum Sovereign",
  "Setessan Champion",
  "Shadow of Mortality",
  "Shalai, Voice of Plenty",
  "Shamanic Revelation",
  "Shambling Vent",
  "Shapesharer",
  "Sharding Sphinx",
  "Shared Animosity",
  "Shared Summons",
  "Sharuum the Hegemon",
  "Shatter the Sky",
  "Sheltered Thicket",
  "Sheoldred, Whispering One",
  "Shield of Kaldra",
  "Shifting Ceratops",
  "Shigeki, Jukai Visionary",
  "Shimmer Dragon",
  "Shineshadow Snarl",
  "Shinka, the Bloodsoaked Keep",
  "Shivan Dragon",
  "Shivan Reef",
  "Shizo, Death's Storehouse",
  "Shrine of the Forsaken Gods",
  "Sickening Shoal",
  "Sidisi, Undead Vizier",
  "Siege-Gang Commander",
  "Sigarda, Champion of Light",
  "Sigarda, Font of Blessings",
  "Sigarda's Summons",
  "Sigil of the Empty Throne",
  "Sigiled Sword of Valeron",
  "Sigrid, God-Favored",
  "Silence",
  "Silent Arbiter",
  "Silent Sentinel",
  "Silklash Spider",
  "Silumgar, the Drifting Death",
  "Silumgar's Command",
  "Silverblade Paladin",
  "Silverwing Squadron",
  "Simic Ascendancy",
  "Simic Manipulator",
  "Single Combat",
  "Sire of Insanity",
  "Sisay, Weatherlight Captain",
  "Skirk Fire Marshal",
  "Skithiryx, the Blight Dragon",
  "Skullbriar, the Walking Grave",
  "Skullclamp",
  "Skullwinder",
  "Skybind",
  "Skyclave Relic",
  "Skyshroud Claim",
  "Skysovereign, Consul Flagship",
  "Slaughter Specialist",
  "Slayers' Stronghold",
  "Sliver Hive",
  "Sliver Hivelord",
  "Sliver Legion",
  "Sliver Overlord",
  "Sliver Queen",
  "Smokestack",
  "Smoldering Marsh",
  "Smothering Tithe",
  "Snapcaster Mage",
  "Sneak Attack",
  "Sol Talisman",
  "Solar Blaze",
  "Solemnity",
  "Somberwald Sage",
  "Song of Totentanz",
  "Sorcerer Class",
  "Sorin Markov",
  "Sorin, Solemn Visitor",
  "Soul of Innistrad",
  "Soul of New Phyrexia",
  "Soul of the Harvest",
  "Soul Partition",
  "Soul Shatter",
  "Soulfire Grand Master",
  "Soul's Majesty",
  "Sovereigns of Lost Alara",
  "Sower of Discord",
  "Spark Double",
  "Spawn of Mayhem",
  "Spawnsire of Ulamog",
  "Spawnwrithe",
  "Spear of Heliod",
  "Spearbreaker Behemoth",
  "Spectral Adversary",
  "Spell Swindle",
  "Spelljack",
  "Spellskite",
  "Spelltithe Enforcer",
  "Spelltwine",
  "Spellweaver Volute",
  "Sphinx of Lost Truths",
  "Sphinx of the Steel Wind",
  "Sphinx of Uthuun",
  "Sphinx-Bone Wand",
  "Sphinx's Revelation",
  "Spinal Embrace",
  "Spinerock Knoll",
  "Spire of Industry",
  "Spirit Bonds",
  "Spit Flame",
  "Spiteful Sliver",
  "Spiteful Visions",
  "Spitting Image",
  "Splendid Reclamation",
  "Sporeweb Weaver",
  "Springjack Pasture",
  "Squall Line",
  "Squee, the Immortal",
  "Squirming Emergence",
  "Squirrel Mob",
  "Sram, Senior Edificer",
  "Staff of Domination",
  "Staff of Nin",
  "Stangg, Echo Warrior",
  "Starfield Mystic",
  "Starfield of Nyx",
  "Starstorm",
  "Steam Augury",
  "Steel Hellkite",
  "Steel Overseer",
  "Steel Seraph",
  "Steelbane Hydra",
  "Stenn, Paranoid Partisan",
  "Stirring Wildwood",
  "Stolen by the Fae",
  "Stolen Identity",
  "Stomping Ground",
  "Stone Haven Outfitter",
  "Stonecoil Serpent",
  "Stoneforge Masterwork",
  "Stonehewer Giant",
  "Storm Herald",
  "Storm Herd",
  "Stormbreath Dragon",
  "Stormcarved Coast",
  "Stormfist Crusader",
  "Stratus Dancer",
  "Strength of the Tajuru",
  "Strionic Resonator",
  "Strixhaven Stadium",
  "Stroke of Genius",
  "Sublime Archangel",
  "Sublime Epiphany",
  "Sudden Demise",
  "Sudden Spoiling",
  "Sulfurous Springs",
  "Sun Titan",
  "Sunblast Angel",
  "Sunforger",
  "Sunken Hollow",
  "Sunken Ruins",
  "Sunrise Sovereign",
  "Sunscorch Regent",
  "Surgehacker Mech",
  "Surrak and Goreclaw",
  "Survival of the Fittest",
  "Swan Song",
  "Swarm Intelligence",
  "Swarmyard",
  "Swiftblade Vindicator",
  "Sword of Body and Mind",
  "Sword of Feast and Famine",
  "Sword of Fire and Ice",
  "Sword of Hearth and Home",
  "Sword of Kaldra",
  "Sword of the Animist",
  "Sword of Truth and Justice",
  "Sword of Vengeance",
  "Sydri, Galvanic Genius",
  "Sygg, River Cutthroat",
  "Sylvan Advocate",
  "Sylvan Anthem",
  "Sylvan Awakening",
  "Sylvan Library",
  "Synthetic Destiny",
  "Syphon Sliver",
  "Sythis, Harvest's Hand",
  "Tainted Field",
  "Tainted Isle",
  "Takeno, Samurai General",
  "Tale's End",
  "Talrand, Sky Summoner",
  "Tameshi, Reality Architect",
  "Tamiyo, Collector of Tales",
  "Tarrian's Journal",
  "Taste of Death",
  "Taurean Mauler",
  "Tazri, Beacon of Unity",
  "Tazri, Stalwart Survivor",
  "Tectonic Giant",
  "Teferi's Ageless Insight",
  "Teleportation Circle",
  "Tempered Steel",
  "Tempest Djinn",
  "Temple Altisaur",
  "Temple Bell",
  "Temple Garden",
  "Temporal Extortion",
  "Temporal Mastery",
  "Tempt with Glory",
  "Tempt with Reflections",
  "Temur Ascendancy",
  "Tendershoot Dryad",
  "Teneb, the Harvester",
  "Terastodon",
  "Tergrid, God of Fright",
  "Terra Eternal",
  "Territorial Allosaurus",
  "Terror of Mount Velus",
  "Terror of Towashi",
  "Terror Tide",
  "Teshar, Ancestor's Apostle",
  "Test of Endurance",
  "Teysa Karlov",
  "Teysa, Envoy of Ghosts",
  "Tezzeret the Seeker",
  "Tezzeret, Master of the Bridge",
  "Thalia, Heretic Cathar",
  "Thassa, Deep-Dwelling",
  "Thassa's Intervention",
  "Thaumatic Compass",
  "The Akroan War",
  "The Antiquities War",
  "The Celestus",
  "The Eternal Wanderer",
  "The Everflowing Well",
  "The Filigree Sylex",
  "The First Sliver",
  "The Gitrog Monster",
  "The Goose Mother",
  "The Kami War",
  "The Kenriths' Royal Funeral",
  "The Locust God",
  "The Mending of Dominaria",
  "The Ozolith",
  "The Reality Chip",
  "The Restoration of Eiganjo",
  "The Temporal Anchor",
  "The Unspeakable",
  "The Ur-Dragon",
  "The World Spell",
  "The World Tree",
  "Theater of Horrors",
  "Thieving Skydiver",
  "Thopter Assembly",
  "Thopter Spy Network",
  "Thought Vessel",
  "Thought-Knot Seer",
  "Thousand Moons Smithy",
  "Thousand-Faced Shadow",
  "Thousand-Year Elixir",
  "Thousand-Year Storm",
  "Thragtusk",
  "Thran Spider",
  "Thran Temporal Gateway",
  "Three Blind Mice",
  "Three Visits",
  "Threefold Thunderhulk",
  "Throne of Eldraine",
  "Throne of Makindi",
  "Throne of the God-Pharaoh",
  "Through the Breach",
  "Tiamat",
  "Tibalt's Trickery",
  "Tidespout Tyrant",
  "Tilonalli's Summoner",
  "Time Reversal",
  "Time Sieve",
  "Time Stretch",
  "Time Warp",
  "Time Wipe",
  "Tireless Tracker",
  "Titania, Protector of Argoth",
  "Titania's Command",
  "Tithe",
  "Tome of the Guildpact",
  "Tomik, Distinguished Advokist",
  "Tooth and Nail",
  "Torbran, Thane of Red Fell",
  "Torens, Fist of the Angels",
  "Torrential Gearhulk",
  "Tovolar, Dire Overlord",
  "Tovolar's Huntmaster",
  "Toxic Deluge",
  "Trading Post",
  "Tragic Arrogance",
  "Training Grounds",
  "Transcendence",
  "Transmogrifying Wand",
  "Traumatize",
  "Traverse the Ulvenwald",
  "Traxos, Scourge of Kroog",
  "Treasure Chest",
  "Treasure Map",
  "Treasury Thrull",
  "Tree of Perdition",
  "Tree of Tales",
  "Treeshaker Chimera",
  "Tribute to Horobi",
  "Tribute to the World Tree",
  "Triskaidekaphile",
  "Triskaidekaphobia",
  "Triumphant Adventurer",
  "True Conviction",
  "Tuktuk the Explorer",
  "Twilight Drover",
  "Twilight Mire",
  "Twilight Shepherd",
  "Twinflame",
  "Tyrant of Discord",
  "Tyrite Sanctum",
  "Tyvar the Bellicose",
  "Tyvar, Jubilant Brawler",
  "Ugin, the Ineffable",
  "Ulamog, the Infinite Gyre",
  "Ulasht, the Hate Seed",
  "Ulvenwald Hydra",
  "Ulvenwald Tracker",
  "Umbra Mystic",
  "Unbound Flourishing",
  "Unbreakable Formation",
  "Unctus, Grand Metatect",
  "Undead Alchemist",
  "Underground River",
  "Undergrowth Champion",
  "Underrealm Lich",
  "Underworld Connections",
  "Unesh, Criosphinx Sovereign",
  "Unmarked Grave",
  "Unnatural Growth",
  "Unscythe, Killer of Kings",
  "Urabrask the Hidden",
  "Urabrask, Heretic Praetor",
  "Urborg Scavengers",
  "Urborg, Tomb of Yawgmoth",
  "Urza's Ruinous Blast",
  "Utter End",
  "Utvara Hellkite",
  "Vadrik, Astral Archmage",
  "Valakut Awakening",
  "Valentin, Dean of the Vein",
  "Valiant Knight",
  "Valkyrie Harbinger",
  "Vampiric Tutor",
  "Vanquisher's Banner",
  "Varragoth, Bloodsky Sire",
  "Vastwood Hydra",
  "Vault of the Archangel",
  "Vault of Whispers",
  "Vedalken Archmage",
  "Vedalken Orrery",
  "Venerable Warsinger",
  "Venser, Shaper Savant",
  "Venser's Journal",
  "Verazol, the Split Current",
  "Verdant Command",
  "Verdant Sun's Avatar",
  "Verdurous Gearhulk",
  "Vicious Shadows",
  "Vigor",
  "Vilis, Broker of Blood",
  "Villainous Wealth",
  "Vindicate",
  "Vindictive Lich",
  "Vineglimmer Snarl",
  "Viridian Zealot",
  "Vito, Thorn of the Dusk Rose",
  "Vivien, Champion of the Wilds",
  "Void Rend",
  "Void Winnower",
  "Voidslime",
  "Volatile Arsonist",
  "Volcanic Vision",
  "Voldaren Estate",
  "Vona, Butcher of Magan",
  "Voracious Dragon",
  "Voracious Hydra",
  "Vorel of the Hull Clade",
  "Vorpal Sword",
  "Vraan, Executioner Thane",
  "Vraska, Golgari Queen",
  "Wake to Slaughter",
  "Wakening Sun's Avatar",
  "Walk the Aeons",
  "Wandering Archaic",
  "Wandering Fumarole",
  "Warstorm Surge",
  "Waste Not",
  "Watery Grave",
  "Wavebreak Hippocamp",
  "Wayward Swordtooth",
  "Weathered Wayfarer",
  "Weatherlight",
  "Weaver of Harmony",
  "Well of Ideas",
  "Westvale Abbey",
  "Wharf Infiltrator",
  "Wheel of Fortune",
  "Whelming Wave",
  "Where Ancients Tread",
  "Whip of Erebos",
  "Whir of Invention",
  "Whirlwind of Thought",
  "Whispering Madness",
  "Whispersteel Dagger",
  "White Sun's Twilight",
  "White Sun's Zenith",
  "Widespread Brutality",
  "Widespread Thieving",
  "Wild Pair",
  "Wild Research",
  "Wild Ricochet",
  "Wildfire",
  "Windborn Muse",
  "Windbrisk Heights",
  "Windfall",
  "Windreader Sphinx",
  "Winds of Rath",
  "Wishclaw Talisman",
  "Witch-Maw Nephilim",
  "Wit's End",
  "Woe Strider",
  "Wolfbriar Elemental",
  "Wooded Bastion",
  "Woodfall Primus",
  "World at War",
  "World Shaper",
  "Worldspine Wurm",
  "Worship",
  "Worst Fears",
  "Wound Reflection",
  "Wrath of God",
  "Wrexial, the Risen Deep",
  "Xander's Lounge",
  "Xathrid Necromancer",
  "Xenagos, God of Revels",
  "Xenagos, the Reveler",
  "Xenograft",
  "Xorn",
  "Yahenni, Undying Partisan",
  "Yarok, the Desecrated",
  "Yasharn, Implacable Earth",
  "Yavimaya Coast",
  "Yavimaya, Cradle of Growth",
  "Yenna, Redtooth Regent",
  "Yeva, Nature's Herald",
  "Yidaro, Wandering Monster",
  "Yore-Tiller Nephilim",
  "Yorion, Sky Nomad",
  "Yorvo, Lord of Garenbrig",
  "Yosei, the Morning Star",
  "Yuan-Ti Malison",
  "Zacama, Primal Calamity",
  "Zagoth Triome",
  "Zealous Conscripts",
  "Zenith Chronicler",
  "Zetalpa, Primal Dawn",
  "Zhur-Taa Ancient",
  "Ziatora, the Incinerator",
  "Zirda, the Dawnwaker",
  "Zombie Apocalypse",
  "Zur the Enchanter",
  "Zur, Eternal Schemer",
  "Zurgo Helmsmasher"
] as const;

export const MTGO_COMMANDER_WORKSHOP_ALIASES: Record<string, string> = {
};

export function getMtgoCommanderWorkshopNames() {
  return MTGO_COMMANDER_WORKSHOP_NAMES.map((name) => {
    const alias = MTGO_COMMANDER_WORKSHOP_ALIASES[name] ?? name;
    return {
      inputName: name,
      lookupName: alias,
    };
  });
}
